### ISSUE TITLE
feat/login 디자인 구현 확인요청

### ISSUE THREAD

**Issue by young24n** [seophohoho/PlanIsJustNow-fe#11]
로그인 페이지의 디자인 작업을 완료했습니다. 확인 후 추가 요구 사항, 수정 사항, 차후 지시 사항 등 피드백 해주시면 감사하겠습니다.
![스크린샷 2024-01-23 164104](https://github.com/seophohoho/PlanIsJustNow-fe/assets/155434352/70634907-e310-4b61-91ec-98d93e0f1808)

**Comment by seophohoho** [comment]
확인이 늦은 점 죄송합니다.
회원가입 페이지로 이동할 수 있도록 추가해주시면 좋을 것 같습니다.

**Comment by young24n** [comment]
추가 및 수정 완료했습니다. 확인해주세요

**Comment by seophohoho** [comment]
확인했습니다.
추가로 회원가입페이지에도 로그인페이지로 이동할 수 있도록 해주세요

**Comment by young24n** [comment]
추가 완료했습니다.
