### ISSUE TITLE
회원가입 페이지 추가 사항.

### ISSUE THREAD

**Issue by seophohoho** [seophohoho/PlanIsJustNow-fe#4]
<img width="898" alt="스크린샷 2024-01-05 오후 3 01 40" src="https://github.com/seophohoho/PlanIsJustNow-fe/assets/123441904/f0e6b3d6-7603-4071-97ad-24bcbe37b555">

'이메일 입력 칸' 주변에 '인증코드 발송' 이라고 하는 버튼 추가 해주세요.

**Comment by young24n** [comment]
추가했습니다 검토바랍니다
