### ISSUE TITLE
Axios Network ERROR

### ISSUE THREAD

**Issue by seophohoho** [seophohoho/PlanIsJustNow-fe#5]
![image](https://github.com/seophohoho/PlanIsJustNow-fe/assets/123441904/89463a17-f3f3-40eb-b3db-1b69af30589e)

CORS 문제인것으로 확인됩니다.
https://leeseong010.tistory.com/117
https://www.datoybi.com/http-proxy-middleware/
https://velog.io/@yunsungyang-omc/React-React-App%EC%97%90%EC%84%9C-CORS-%EC%9D%B4%EC%8A%88-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0
위에 블로그들을 참고해서 수정하고 다시 푸시해주시면 될 듯 합니다 :)

**Comment by young24n** [comment]
푸시 했습니다 확인해주세요
