### ISSUE TITLE
signup2 디자인 완성 확인 요청

### ISSUE THREAD

**Issue by young24n** [seophohoho/PlanIsJustNow-fe#8]
디자인 완성했습니다. 확인해주시고 추후 post 관련 지시사항 요청드립니다.
![스크린샷 2024-01-17 152030](https://github.com/seophohoho/PlanIsJustNow-fe/assets/155434352/d1e8f711-e8b1-408d-802f-60869d3dfad7)

**Comment by seophohoho** [comment]
확인했습니다.
'state전달' 문구에는 펫 종 이름이 들어가고, 
'state전달예정 설명'문구에는 펫 종에 대한 설명이 들어가도록 나중에 수정하면 되겠습니다.
http body 들어갈 값은 내일 말씀드리겠습니다.
